apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-initdb-config
  namespace: k8s-program
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS post_ (
        id bigint NOT NULL PRIMARY KEY,
        content varchar(255),
        topic varchar(255),
        user_id bigint
    );