spring:
  application:
    name: user-service

  datasource:
    url:  ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false

server:
  port: 8080


management:
  endpoint:
    health:
      probes:
        enabled: true