apiVersion: v1
kind: ConfigMap
metadata:
  name: users-initdb-config
  namespace: k8s-program
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS user_ (
        id bigint NOT NULL PRIMARY KEY,
        name varchar(255),
        number_of_posts varchar(255)
    );