apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-db-volume-1
  namespace: k8s-program
spec:
  storageClassName: users-db-volume-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/users
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop