apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program
  labels:
    name: k8s-program

---
apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  namespace: k8s-program
type: Opaque
data:
  username: YWRtaW4K #admin
  password: cGFzc3dvcmQxMjM= #password123

---
apiVersion: v1
kind: Secret
metadata:
  name: posts-db-secret
  namespace: k8s-program
type: Opaque
data:
  username: YWRtaW4K #admin
  password: cGFzc3dvcmQxMjM= #password123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-program-config-map
  namespace: k8s-program

data:
  # property-like keys; each key maps to a simple value
  USERS_SPRING_DATASOURCE_URL: "jdbc:postgresql://user-db:5432/users"

  POSTS_SPRING_DATASOURCE_URL: "jdbc:postgresql://post-db:5432/posts"

  USER_SERVICE_URL: "http://user-service-service.k8s-program.svc.cluster.local:8080/users/"


