apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: k8s-program

spec:
  replicas: 2

  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 3
        maxUnavailable: 1

  selector:
    matchLabels:
      app: user-service
      version: v1

  template:
    metadata:
      labels:
        app: user-service
        version: v1

    spec:
      containers:
        - name: user-service
          image: epamanastasiiasolomakhina/user-service:1.0.8
          env:
            # Define the environment variable
            - name: SPRING_DATASOURCE_URL
              # from the key name in the ConfigMap.
              valueFrom:
                configMapKeyRef:
                  name: k8s-program-config-map          # The ConfigMap this value comes from.
                  key: USERS_SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: username
                  optional: false

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: password
                  optional: false

          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 30

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: k8s-program

spec:
  type: NodePort #type of the service
  selector:
    app: user-service

  ports:
    - protocol: TCP
      port: 8080 #port that the service is running on the cluster
      targetPort: 8080 #exposed by the service
